spring:
  application:
    name: web-crawler

  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: web_crawler
      host: localhost
      port: 27017

